### ISSUE TITLE
Sad scrollbar 

### ISSUE THREAD

**Issue by TieWay59** [roife/roife.github.io#1]
![图片](https://user-images.githubusercontent.com/40034603/91918998-26c8ea00-ecf7-11ea-8e4e-a9649301259b.png)
*screen shoot from my google chrome*

If you don't think it's awkward, just keep it simple.

Here is one inspiring reference: [The Modern Way to Style Scrollbars](https://alligator.io/css/css-scrollbars/)

And a good practice :
![图片](https://user-images.githubusercontent.com/40034603/91919662-3f3a0400-ecf9-11ea-9f3a-97c647ed5652.png)

BTW, dude have a good rest at midnight.

**Comment by roife** [comment]
Thanks a lot for your advice and the reference. I will fix them (both the ugly scrollbar and the habit of staying up late XD).
